### ISSUE TITLE
FunctionClauseError) no function clause matching in Bandit.HTTP1.Handler.handle_info/2

### ISSUE THREAD

**Issue by phanmn** [mtrudel/bandit#233] opened 2023-09-19 04:23 UTC
Hi, first of all thank you for your awesome library.

Yesterday, I saw this issue, can you please check it, many thanks!

deps/thousand_island/lib/thousand_island/handler.ex:5: Bandit.HTTP1.Handler.handle_info({#Reference<0.736885023.3819503617.224524>, :ok}, {%ThousandIsland.Socket{socket: #Port<0.1553>, transport_module: ThousandIsland.Transports.TCP, read_timeout: 60000, span: %ThousandIsland.Telemetry{span_name: :connection, telemetry_span_context: #Reference<0.736885023.3819438082.144351>, start_time: -576458810641083835, start_metadata: %{parent_telemetry_span_context: #Reference<0.736885023.3815768066.116439>, remote_address: {0, 0, 0, 0, 0, 65535, 2700, 10}, remote_port: 60086, telemetry_span_context: #Reference<0.736885023.3819438082.144351>}}}, %{handler_module: Bandit.HTTP1.Handler, http_1_enabled: true, http_2_enabled: true, opts: %{http_1: [], http_2: [], websocket: []}, plug:

**Comment by mtrudel** [comment] 2023-09-19 12:54
This is cut from the same essential cloth as https://github.com/mtrudel/bandit/issues/218, https://github.com/mtrudel/bandit/issues/141, https://github.com/mtrudel/bandit/issues/84, https://github.com/mtrudel/thousand_island/issues/83 and a few others. You aren't able to send messages to HTTP handler processes because Plug provides no way to surface them up to your application code.

**Comment by mtrudel** [comment] 2023-09-19 12:54
Closing for hygiene. If the above pointers do NOT in fact answer the issue, please feel free to reopen!

Thanks for the issue!

**Closed by mtrudel** 2023-09-19 12:54 UTC

**Comment by phanmn** [comment] 2023-09-20 04:19
So it works normally right @mtrudel ?

**Comment by mtrudel** [comment] 2023-09-20 12:47
Yep, this is 100% expected behaviour for the situation you're in. I have plans to revisit the plug interface to make things like this easier (and to accommodate gRPC and other more complex uses of http) but that's a large project that will touch many projects beyond just Bandit and won't be coming until 2.0 or even later

**Comment by phanmn** [comment] 2023-09-21 04:41
Many thanks
